title: Aupala Bhattacharyya
#logo: /assets/img/headshot_circle.png
description: Analyst | Turning Data into Strategic Decisions| MSBA Candidate at UW Madison | SQL • Tableau • Power BI • ETL • Python
show_downloads: true
theme: jekyll-theme-minimal
